app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
]

status/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls', namespace='app'))
]

app/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms


class NewForm(forms.Form):
    text = forms.CharField(max_length=1000)
    choice = forms.CharField(widget=forms.RadioSelect(choices=[('char','charEncrypt'),('sym','symEncrypt')]))

app/views.py
from django.shortcuts import render
from .forms import NewForm
# Create your views here.


def index(request):
    alpha = {'A':'4', 'H':'#', 'k':'!<', 'K':'!<', 'S':'$', 'z':'2', 'Z':'2', 'Y':'`/', 'U':'(_)', 'D':'[)', 'O':'()',
             'B':'ß','C':'(','L':'!_','x':'><','t':'+','E':'£','Ṯ':'+','s':'5','a':'@','v':'\/','V':'\/','i':'ï','o':'ø',
             'b':'þ'}
    rev = {}
    for i in range(26):
        rev[chr(97+i)] = chr(122-i)
    data = ''
    def l1(text):
        temp = ''
        def replace_index(text, index=0, replacement=''):
            return '%s%s%s' % (text[:index], replacement, text[index + 1:])
        for i in range(len(text)):
            if (ord(text[i])>64 and ord(text[i])<91) or (ord(text[i])>96 and ord(text[i])<123):
                if text[i].islower():
                    text = replace_index(text,i,rev[text[i]])
                else:
                    text = replace_index(text, i, rev[text[i].lower()].upper())
        return text
    def symbol(text):
        for i in range(len(text)):
            try:
                text = text.replace(text[i],alpha[text[i]])
            except:
                pass
        return text
    if request.method == "POST":
        form = NewForm(request.POST)
        text = ""
        if form.is_valid():
            text = str(form.cleaned_data['text'])
            choice = str(form.cleaned_data['choice'])
            if choice == 'char':
                data = l1(text)
            else:
                data = symbol(text)
        return render(request,'app/index.html',{'data': data, 'form': form})
    else:
        form = NewForm()
    return render(request,'app/index.html',{'data': data, 'form': form})

app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StatCryptor</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <style>
        #div{
            width: 50%;
            margin: auto;
            border: 2px dashed #dddddd;
            padding: 15px;
            border-radius: 6px;
            box-shadow: 4px 8px 7px grey;
        }
        textarea{
            border-radius: 5px;
            width:inherit;
        }
        @media (max-width: 768px) {
            textarea{
                width:inherit;
            }
            #div{
                width: 85%;
            }
        }
    </style>
    <script>
        function myFunction() {

            var copyText = document.getElementById("myInput");

            copyText.select();

            document.execCommand("copy");

        }
    </script>
</head>
<body>
    <br>
    <marquee>{Paste your whatsapp text status to encrypt in any of the two below methods}</marquee>
    <br>
    <div align="center" id="div">
        <h3>Status Encryptor</h3>
        <form action="{% url 'app:index' %}" method = "POST" name="form">
            {% csrf_token %}
            <div>
                <input class="form-control" type = "text" name="text" placeholder="Enter status text">
            </div>
            <br>
                <input type = "radio" name="choice" value="char">charEncrypt<br>
                <input type = "radio" name="choice" value="sym">symEncrypt
            <br><br>
            <div>
                <input type="submit" value="Encrypt" class="btn btn-primary">
            </div>
        </form>
        <br><br>
        Encrypted Result:<br>
        <textarea rows="5" id="myInput">{{data}}</textarea><br>

        <button class="btn btn-primary" onclick="myFunction()">Copy text</button>
    </div>
</body>
</html>